## ________ Packages required for the analysis ________ ##
# if (!requireNamespace("BiocManager", quietly = TRUE))
# install.packages("BiocManager")
# if (!requireNamespace("devtools", quietly = TRUE))
# install.packages("devtools")
# BiocManager::install("DESeq2")
# BiocManager::install("tximport")
# BiocManager::install("Glimma")
# BiocManager::install("edgeR")
# BiocManager::install("limma")
# BiocManager::install("biomaRt")
# devtools::install_github("https://github.com/jokergoo/ComplexHeatmap")
# BiocManager::install("circlize")
# devtools::install_github("https://github.com/sinhrks/ggfortify")
# BiocManager::install("RColorBrewer")
# install.packages("tidyverse", "broom", "here")
library(tidyverse)
library(ComplexHeatmap)
library(circlize)
library(RColorBrewer)
library(ggfortify)
library(limma)
library(Glimma)
library(edgeR)
library(tidyverse)
library(tximport)
library(DESeq2)
library(RColorBrewer)
library(broom)
library(fmsb)
mainDir <- getwd()
dir.create(file.path("Supplemental"), showWarnings = FALSE)
dir.create(file.path("Figures"), showWarnings = FALSE)
dir.create(file.path("Figures/Figure2"), showWarnings = FALSE)
dir.create(file.path("Figures/Figure3"), showWarnings = FALSE)
dir.create(file.path("Figures/Figure4"), showWarnings = FALSE)
dir.create(file.path("Figures/Figure5"), showWarnings = FALSE)
dir.create(file.path("Figures/Figure6"), showWarnings = FALSE)
dir.create(file.path("Data/Fibroblasts/ProcessedData"), showWarnings = FALSE)
dir.create(file.path("Data/GTEx/ProcessedData"), showWarnings = FALSE)
dir.create(file.path("Data/HumanProteinAtlas/ProcessedData"), showWarnings = FALSE)
dir.create(file.path("Data/MitoCarta/ProcessedData"), showWarnings = FALSE)
options(warn=-1) ## optional to suppress warning messages. Details on the warning messages can be extracted using warnings()
#options(warn=0) ## turn on warning messages

## Code for Figure 2, Supplemental Figures S2 and S3
source("Code/Figure2/Fig2A-B_MouseData.R")
source("Code/Figure2/Fig2D-E_HumanProteinAtlas.R")
source("Code/Figure2/Fig2F-I_GTEx.R") 
source("Code/Figure2/SupplFig3_GTEx_TPMvsTMM.R")

## Code for Figure 3
source("Code/Figure3/Figure3_C-D.R")
source("Code/Figure3/Gene_to_pathway_levels.R")

## Code for Figure 4, Supplemental Figures S4 + S5
source("Code/Figure4/Figure4.R")
source("Code/Figure4/Suppl_FigureS5_Conceptual_Figure.R")

## Code for Figure 5, Supplemental Figures S6 and S7
source("Code/Figure5/MitoPPS_calculation.R")
source("Code/Figure5/Fig5A_Heatmap.R")
source("Code/Figure5/Fig5B_C_D_PCAs.R")
source("Code/Figure5/Suppl_FigS7_Barplots.R")

## Code for Figure 6, Supplemental Figures S8, S9, and S10
rmarkdown::render(input = 'Code/Figure6/1_RNAseq_normalization_prep.Rmd')
source("Code/Figure6/2_Fig6A-F_DataPreparation.R")
source("Code/Figure6/3_Fig6A-F_Figures.R")
source("Code/Figure6/4_Fig6G-H_DataPreparation.R")
source("Code/Figure6/5_Fig6G-H_Figures.R")
